build: disable `win_arm64` for now
build fails with

> error: linking with `link.exe` failed: exit code: 1120

because of `libz_sys` and `libgit2_sys` (`warning LNK4272: library
machine type 'ARM64' conflicts with target machine type 'x64'`)